# Generated by Django 4.2.1 on 2023-06-20 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ComunicadoCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=100)),
                ('lavoura_lat', models.FloatField()),
                ('lavoura_lon', models.FloatField()),
                ('lavoura_tipo', models.SmallIntegerField()),
                ('lavoura_data_colheita', models.DateTimeField()),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evento', to='core.evento')),
            ],
        ),
    ]
